# Manuscript colors for Kitty terminal
foreground #f2ecce
background #20262a
cursor #f2ecce
cursor_text_color #1f2428
selection_foreground #1f2428
selection_background #79b8ff

# Normal colors
color0 #586069
color1 #ea4a5a
color2 #34d058
color3 #e5c07b
color4 #2188ff
color5 #aa7ed3
color6 #39c5cf
color7  #dcd7ba

# Bright colors
color8  #959da5
color9  #f97583
color10 #85e89d
color11 #ffea7f
color12 #79b8ff
color13 #b392f0
color14 #56d4dd
color15 #f2ecce
